article/urls.py
from django.urls import re_path

from . import views

app_name = 'article'

urlpatterns = [
    re_path(r'articles/get/(?P<article_id>\d+)/$', views.article, name="article"),
    re_path(r'^$', views.articles, name='articles'),
    re_path(r'articles/add_like/(?P<article_id>\d+)/$', views.add_like, name="add_like"),
    re_path(r'articles/add_comment/(?P<article_id>\d+)/$', views.add_comment, name="add_comment"),
]

firstapp/urls.py
from django.contrib import admin
from django.urls import re_path, include


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('article.urls')),
    re_path(r'^auth/', include('loginsys.urls')),
   ]

loginsys/urls.py
from django.urls import re_path

from . import views

app_name = 'loginsys'

urlpatterns = [
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
]

titleapp/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^', views.title),
]

article/models.py
from django.db import models
from django.utils.encoding import smart_text


# Create your models here.
class Article(models.Model):
    class Meta():
        db_table = "article"

    title = models.CharField(max_length=200)
    text = models.TextField()
    date = models.DateTimeField()
    likes = models.IntegerField(default=0)

    def __str__(self):
        return smart_text(self.title)


class Comments(models.Model):
    class Meta():
        db_table = 'comments'

    text = models.TextField(verbose_name="Комментарий:")
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

loginsys/models.py
from django.db import models

# Create your models here.

titleapp/models.py
from django.db import models
from django.utils.encoding import smart_text


# Create your models here.

class Header(models.Model):
    class Meta():
        db_table = "header"

    title = models.CharField(max_length=100)

    def __str__(self):
        return smart_text(self.title)

article/forms.py
from django.forms import ModelForm
from .models import Comments


class CommentForm(ModelForm):
    class Meta():
        model = Comments
        fields = ['text']

article/views.py
from django.shortcuts import render_to_response, redirect
from django.http.response import HttpResponse, Http404
from django.template.context_processors import csrf
from django.template.loader import get_template

from .forms import CommentForm
from django.urls import reverse

from .models import Article, Comments
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import auth
from django.core.paginator import Paginator


# Create your views here.
def basic_one(request):
    view = "basic_one"
    html = "<html><body>This is %s view</body></html>" % view
    return HttpResponse(html)


def template_two(request):
    view = "template_two"
    template = get_template('myview.html')
    html = template.render({"name": view})
    return HttpResponse(html)


def template_three_simple(request):
    view = "template_three"
    return render_to_response('myview.html', {"name": view})


def articles(request, page_number=1):
    all_articles = Article.objects.all().order_by("-date")
    current_page = Paginator(all_articles, 2)
    return render_to_response('articles.html',
                              {"articles": current_page.page(page_number),
                               "username": auth.get_user(request).username})


def article(request, article_id=1):
    comment_form = CommentForm
    args = {}
    args.update(csrf(request))
    args['article'] = Article.objects.get(id=article_id)
    args['comments'] = Comments.objects.filter(article_id=article_id)
    args['form'] = comment_form
    args['username'] = auth.get_user(request).username
    return render_to_response('article.html', args)


def add_like(request, article_id):
    response = redirect(reverse('article_app:articles'))
    if article_id in request.COOKIES:
        return response
    try:
        article = Article.objects.get(id=article_id)
        article.likes += 1
        article.save()
        response = redirect(reverse('article_app:articles'))
        response.set_cookie(article_id, "test")
    except ObjectDoesNotExist:
        raise Http404
    return response


def add_comment(request, article_id):
    if request.POST and ("pause" not in request.session):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            try:
                comment.article = Article.objects.get(id=article_id)
            except ObjectDoesNotExist:
                raise Http404
            form.save()
            request.session.set_expiry(60)
            request.session['pause'] = True
    return redirect(reverse('article_app:article', args=[article_id]))

loginsys/views.py
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, render_to_response

# Create your views here.
from django.template.context_processors import csrf
from django.urls import reverse


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect(reverse('article_app:articles'))
        else:
            args['login_error'] = 'Пользователь не найден'
            return render_to_response('login.html', args)
    else:
        return render_to_response('login.html', args)


def logout(request):
    auth.logout(request)
    return redirect(reverse('article_app:articles'))

def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm
    if request.POST:
        newuser_form = UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'],
                                        password=newuser_form.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect(reverse('article_app:articles'))
        else:
            args['form'] = newuser_form
    return render_to_response('register.html', args)

titleapp/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponse


from .models import Header
# Create your views here.


def title(request):
    return render_to_response('title.html', {"header": Header.objects.get(id=1)})

article/templates/article.html
{% extends 'main.html' %}
{% load static %}

{% block article %}
<h6>Дата публикации: {{article.date}}</h6>
<h4>{{article.title}}</h4>
<p> {{article.text}} </p>
<p><img src="{% static 'ParkOmaha-icons-ltBLUE_thumbsup.png' %}" width="25px" height="25px">{{article.likes}} </p>
<hr>
<div class="large-offset-1 large-8 columns">
    <p>Комментарии:</p>
    {% for comment in comments %}
    <p>{{comment.text}}</p>

    {% endfor %}


    {% if username %}

    <form action="{% url 'article_app:add_comment' article.id %}" method="post">

        {% csrf_token %}
        {{ form }}
        <input type="submit" class="button" value="Добавить комментарий">
    </form>

    {% endif %}
    {% endblock %}
</div>

article/templates/articles.html
{% extends 'main.html' %}
{% load static %}

{% block article %}
<div class="large-offset-1 row">
    {% for article in articles %}
    <h6>Дата публикации: {{article.date}}</h6>
    <h4><a href="/articles/get/{{article.id}}">{{article.title}} </a></h4>
    <p> {{article.text}} </p>
    <p><a href="/articles/add_like/{{article.id}}"><img src="{% static 'ParkOmaha-icons-ltBLUE_thumbsup.png' %}" width="25px"
                                         height="25px"> </a>{{article.likes}} </p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

loginsys/templates/login.html
{% extends 'main.html' %}

{% block login %}
<div class="large-offset-3 large-8 columns" >
    <form action="{% url 'loginsys:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Имя пользователя: </label>
        <input type="text" name="username" id="username">
        <label for="password">Пароль: </label>
        <input type="password" name="password" id="password">
        {% if login_error %}
        <label class="error">{{login_error}}</label>
        {% endif %}
        <input class="button" type="submit" value="Войти">

        <div class="label round secondary">
            <a href="{% url 'loginsys:register' %}">Регистрация</a>
        </div>

    </form>
</div>
{% endblock %}

loginsys/templates/register.html
{% extends 'main.html' %}

{% block login %}

<div class="large-offset-3 large-6 columns">
    <form action="{% url 'loginsys:register' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input class="button" type="submit" value="Зарегистрироваться">
    </form>
</div>

{% endblock %}

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/foundation.css' %}">
</head>
<body>

<div class="top-bar">
    <section class="top-bar-section">
        <ul class="right">
            {% if username %}
            <li><a href="{% url 'loginsys:logout' %}">Выйти {{username}}</a>  </li>
            {% else %}
            <li><a href="{% url 'loginsys:login' %}">Войти</a>  </li>
            {% endif %}
        </ul>
    </section>
</div>
<h1><a href="/"> Мой блог</a></h1>

{% block login %} {% endblock %}
{% block article %}  {% endblock %}



</body>
</html>

templates/myview.html
<!DOCTYPE html>
<html>

<body>
This is {{ name }} view
</body>
</html>

titleapp/templates/title.html
{% extends 'main.html' %}

{% block header %}
<h1>{{header.title}}</h1>

{% endblock %}